### ISSUE TITLE
some flags

### ISSUE THREAD

**Issue by Kantaiso** [ebinBuddha/4chan-Flag-Fixer#1]

**Comment by Kantaiso** [comment]
forgot the flags
![Thailand](https://user-images.githubusercontent.com/11905445/59531943-3236b800-8e9c-11e9-9c72-a4c719c6efbe.png)
![Afghanistan](https://user-images.githubusercontent.com/11905445/59531945-3236b800-8e9c-11e9-8f14-c1bf741bdf5a.png)
![Mauritania](https://user-images.githubusercontent.com/11905445/59531947-3236b800-8e9c-11e9-98ab-eb170c26e85b.png)

**Comment by ebinBuddha** [comment]
(You)
